version: 2.1

executors:
  default:
    docker:
      - image: circleci/ruby:2.6.6-node-browsers
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          RAILS_ENV: test

commands:
  setup:
    steps:
      - restore_cache:
          keys:
            - gem-chace-v1-{{ checksum "Gemfile.lock" }}
            - gem-chace-v1

      - run:
          name: Update bundler
          command: gem update bundler

      - run:
          name: Set bundle config clean
          command: bundle config set clean "true"

      - run:
          name: Install gems
          command: bundle check || bundle install

      - save_cache:
          key: gem-chace-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - restore_cache:
          keys:
            - yarn-chace-v1-{{ checksum "yarn.lock" }}
            - yarn-chace-v1

      - run:
          name: Yarn Install
          command: yarn install --cache-folder ~/.cache/yarn

      - save_cache:
          key: yarn-chace-v1-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

jobs:
  test:
    executor: default
    steps:
      - checkout
      - setup
      - run:
          name: Run rubocop
          command: bundle exec rubocop -c .rubocop.yml

      - run:
          name: Run RSpec
          command: bundle exec rspec

      - store_test_results:
          path: tmp/test-results

      - store_artifacts:
          path: tmp/screenshots
          destination: screenshots

workflows:
  version: 2.1

  build_and_test:
    jobs:
      - test
