default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: unicode
  username: postgres
  password: password

development:
  <<: *default
  host: db
  host: <%= ENV['DB_HOST'] || 'db' %>
  database: sound_links_development

test:
  <<: *default
  database: sound_links_test

production:
  <<: *default
  database: sound_links_production
