# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.0.3"

# default
gem "rails", "7.0.0"
# gem "sqlite3", "~> 1.4"
gem "puma"
gem "sass-rails"
# gem "webpacker", "~> 4.0"
# gem "turbolinks", "~> 5"
gem "bootsnap", require: false
gem "jbuilder"

# not default
gem "jwt"
gem "faraday"
gem "pg"
gem "kaminari"
gem "rack-cors"

# 4.0だと以下のエラーが発生したためバージョンを下げた
# ref: https://github.com/rails/sprockets-rails/issues/444#issue-504540500
gem "sprockets", "~>3.0"

group :development, :test do
  gem "byebug", platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  # gem "web-console", ">= 3.3.0"
  gem "listen"
  gem "spring"
  gem "spring-watcher-listen", "~> 2.0.0"

  # not default
  gem "rubocop", require: false
  gem "rubocop-performance"
  gem "rubocop-rails"
  gem "rubocop-rspec"
end

group :test do
  # gem "capybara", ">= 2.15"
  # gem "selenium-webdriver"
  # gem "webdrivers"

  # not default
  gem "rspec-rails"
  gem "factory_bot"
  gem "webmock"
  gem "simplecov", require: false
end
