# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.0.3'

# default
gem 'rails', '7.0.0'
gem 'puma'
gem 'bootsnap', require: false
gem 'jbuilder'

# not default
gem 'jwt'
gem 'faraday'
gem 'pg'
gem 'kaminari'
gem 'rack-cors'

group :development, :test do
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
end

group :development do
  # default
  gem "web-console"

  # not default
  gem 'rubocop', require: false
  gem 'rubocop-performance'
  gem 'rubocop-rails'
  gem 'rubocop-rspec'
end

group :test do
  # not default
  gem 'rspec-rails'
  gem 'factory_bot'
  gem 'webmock'
  gem 'simplecov', require: false
end
